# -*- coding: utf-8 -*-
"""Advanced Plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dROiU96e34IxtNX7M0NblbXPZkdn09W4
"""

import matplotlib.pyplot as plt
from matplotlib.widgets import SpanSelector
!pip install matplotlib==3.3.4

def onselect(xmin, xmax):
            print(xmin, xmax)
            return xmin, xmax
fig, ax = plt.subplots()
ax.plot([1,2,3,4,5,6,7], [10, 50, 100, 23,15,28,45])
span = SpanSelector(ax, onselect, 'horizontal', useblit=True,  rectprops=dict(alpha=0.5, facecolor='red'))
plt.show()

import matplotlib.pyplot as plt
#Defining the x and y ranges
xranges = [(5,5), (20,5),(20,7)]
yrange = (2,1)
#Plotting the broken bar chart
plt.broken_barh(xranges, yrange, facecolors='green')
xranges = [(6,2), (17,5),(50,2)]
yrange = (15,1)
plt.broken_barh(xranges, yrange, facecolors='orange')
xranges = [(5,2), (28,5),(40,2)]
yrange = (30,1)
plt.broken_barh(xranges, yrange, facecolors='red')
plt.xlabel('Sales')
plt.ylabel('Days of the Month')
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

x = np.random.rand(5, 8)*.7
plt.plot(x.mean(axis=0), '-o', label='average per column')
plt.xticks([])

plt.table(cellText=[['%1.2f' % xxx for xxx in xx] for xx in x],cellColours=plt.cm.GnBu(x),loc='bottom')

plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

x = np.random.rand(5, 8)*.7
plt.plot(x.mean(axis=0), '-o', label='average per column')
plt.xticks([])

plt.table(cellText=[['%1.2f' % xxx for xxx in xx] for xx in x],cellColours=plt.cm.RdPu(x),loc='top')

plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

x = np.random.rand(5, 8)*.7
plt.plot(x.mean(axis=0), '-o', label='average per column')
plt.xticks([])

plt.table(cellText=[['%1.2f' % xxx for xxx in xx] for xx in x],cellColours=plt.cm.YlGn(x),loc='top')

plt.show()

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import numpy as np
import matplotlib.image as image
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('income.csv')
im = image.imread('LeBron_James.jpeg') # Image

# The dataset consists of income of a number of athletes. Let’s filter out the data consisting of only Lebron.
lebron_james = df[df['Name']=='LeBron James']

# Displaying the watermarked plot.
fig, ax = plt.subplots()
#The matplotlib.pyplot.subplots method provides a way to plot multiple plots on a single figure.
#Given the number of rows and columns, it returns a tuple (fig, ax), giving a single figure fig with an array of axes ax.
ax.grid()
ax.plot('Year','earnings ($ million)',data=lebron_james)
ax.set_title("LeBron James earnings in US$(millions)")
fig.figimage(im, 60, 40,cmap='ocean', alpha=.2)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('india_gdp.csv', parse_dates=['Year'])
df['Year'] = df['Year'].apply(lambda x: pd.Timestamp(x).strftime('%Y'))

#calling xkcd() method
plt.xkcd(scale=5, length=400)
df.plot(x='Year',y='GDP Growth (%)',kind='bar')
plt.ylabel('GDP Growth (%)')
plt.xticks(rotation=-20)
plt.figure(figsize=(10,8))
plt.show()