# -*- coding: utf-8 -*-
"""Grammar Of Graphics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ulFEQuNtfM8gNmFp58i-hVOqJNwVMvxS
"""

import pandas as pd
reviews = pd.read_csv("winemag_data_130k_v2.csv", index_col=0)
reviews.head(3)

from plotnine import *

top_wines = reviews[reviews['variety'].isin(reviews['variety'].value_counts().head(5).index)]

print(top_wines)

"""Our starting point is a simple scatter plot:"""

df = top_wines.head(1000).dropna()

(ggplot(df)
 + aes('points', 'price')
 + geom_point())

"""**We can add a regression line with a stat_smooth layer**"""

df = top_wines.head(1000).dropna()

(
    ggplot(df)
        + aes('points', 'price')
        + geom_point()
        + stat_smooth()
)

"""**To add color, add an aes with color**"""

df = top_wines.head(1000).dropna()

(
    ggplot(df)
        + geom_point()
        + aes(color='points')
        + aes('points', 'price')
        + stat_smooth()
)

"""**To apply faceting, use facet_wrap**"""

df = top_wines.head(1000).dropna()

(ggplot(df)
     + aes('points', 'price')
     + aes(color='points')
     + geom_point()
     + stat_smooth()
     + facet_wrap('~variety')
)

"""**So  far we have had the chart aesthetic (aes) appear as a separate functional element; however, aes can also appear as a layer parameter:**"""

(ggplot(df)
 + geom_point(aes('points', 'price'))
)

"""**Or as a parameter in the overall data:**"""

(ggplot(df, aes('points', 'price'))
 + geom_point()
)

"""**Geometries are the core of plotnine, which comes with a variety of geometries of varying levels of complexity. For example, a poltnine bar plot is geom_bar:**"""

(ggplot(top_wines)
     + aes('points')
     + geom_bar()
)

"""**The plotnine equivalent of a hexplot, a two-dimensional histogram, is geom_bin2d**"""

(ggplot(top_wines)
     + aes('points', 'variety')
     + geom_bin2d(bins=20)
)

"""**Now using facet_wrap; coord_fixed and ggtitle are two more.**"""

(ggplot(top_wines)
         + aes('points', 'variety')
         + geom_bin2d(bins=20)
         + coord_fixed(ratio=1)
         + ggtitle("Top Five Most Common Wine Variety Points Awarded")
)

pokemon = pd.read_csv('pokemon.csv', index_col=0)\
                        .rename(columns=lambda x: x.replace(" ", "_"))
pokemon.head(3)